[workspace]
members = [".", "migration", "editor"]

[package]
name = "memm"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
sea-orm = { version = "1", features = ["sqlx-sqlite", "runtime-tokio-rustls", "macros"] }
sea-orm-migration = { version = "1", features = ["runtime-tokio-rustls", "sqlx-sqlite"] }
clap = { version = "4.6.5", features = ["derive"] }
anyhow = "1.0.104"
chrono = "0.4"
migration = { path = "migration" }
editor = { path = "editor" }
